//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantApp.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppOrders()
        {
            this.AppOrderDetails = new HashSet<AppOrderDetails>();
        }
    
        public int OrderId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> TableId { get; set; }
        public string OrderType { get; set; }
        public string Status { get; set; }
        public decimal TotalAmount { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string OrderNote { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<decimal> CashAmount { get; set; }
        public Nullable<decimal> CreditCardAmount { get; set; }
        public Nullable<decimal> MealCardAmount { get; set; }
        public string PaymentType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppOrderDetails> AppOrderDetails { get; set; }
        public virtual AppTables AppTables { get; set; }
        public virtual AppUsers AppUsers { get; set; }
    }
}
