//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantApp.Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppProducts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppProducts()
        {
            this.AppOrderDetails = new HashSet<AppOrderDetails>();
        }
    
        public int ProductId { get; set; }
        public int CategoryId { get; set; }
        public string ProductName { get; set; }
        public decimal Price { get; set; }
        public string ImageUrl { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public bool IsAvailable { get; set; }
        public string Description { get; set; }
    
        public virtual AppCategories AppCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppOrderDetails> AppOrderDetails { get; set; }
        public virtual Companies Companies { get; set; }
    }
}
