//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantApp.Web.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RestaurantAppDBEntities : DbContext
    {
        public RestaurantAppDBEntities()
            : base("name=RestaurantAppDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppCategories> AppCategories { get; set; }
        public virtual DbSet<AppOrderDetails> AppOrderDetails { get; set; }
        public virtual DbSet<AppOrders> AppOrders { get; set; }
        public virtual DbSet<AppProducts> AppProducts { get; set; }
        public virtual DbSet<AppTables> AppTables { get; set; }
        public virtual DbSet<AppUsers> AppUsers { get; set; }
        public virtual DbSet<Companies> Companies { get; set; }
    }
}
